name: 🐛 Bug Report
description: Create a report to help us improve
title: '[BUG] - Short, descriptive summary'
labels: bug
assignees: 'jurgenjacobsen'

body:
  - type: textarea
    id: description
    attributes:
      label: '📝 Description'
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: '🚶 Steps to Reproduce'
      description:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: '🎯 Expected Behavior'
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: '📸 Screenshots / Recordings'
      description: If applicable, add screenshots or a screen recording to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: '💻 Environment Information'
      description: ->
        * **OS:** [e.g. iOS, Windows 11]
        * **Browser:** [e.g. Chrome, Safari]
        * **Version:** [e.g. 22]
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: '🔍 Additional Context'
      description: Add any other context about the problem here (e.g., logs, stack traces, or "this only happens on Tuesdays").
    validations:
      required: false
